services:
  - type: web
    name: clean-flutter-backend
    runtime: node
    plan: free
    rootDirectory: server
    buildCommand: npm install --production=false && node node_modules/prisma/build/index.js generate && node node_modules/typescript/lib/tsc.js -p .
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        value: http://localhost:3000,https://localhost:3000
