services:
  - type: web
    name: clean-flutter-backend
    runtime: node
    plan: free
    rootDirectory: server
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGINS
        value: http://localhost:3000,https://localhost:3000
