[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npx prisma generate', 'npm run build']

[phases.start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
